import esbuild from "esbuild";
import process from "process";
import builtInModules from "builtin-modules";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const isWatch = process.argv.includes("--watch");

const buildOptions = {
	banner: { js: banner },
	target: "ES2021",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	minify: prod,
	format: "cjs",
	mainFields: ["browser", "module", "main"],
	conditions: ["browser"],
	outfile: "main.js",
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtInModules,
	],
};

if (isWatch) {
	const context = await esbuild.context(buildOptions);
	await context.watch();
	console.log("Watching for changes...");
} else {
	await esbuild.build(buildOptions);
	console.log("Build complete -> main.js");
}
